// Bouquet photos: picked on Pinterest, ribbons removed + blue-screened in Google Flow (Nano Banana Pro),
// background keyed out locally (see CREDITS.md).
// grip = point on the stems where the fist holds (0–1 of the image),
// size = image height ÷ knuckle span, so every bouquet looks equally big in the hand.
export const BOUQUETS = [
  {
    id: "tulip-putih", name: "White tulips", latin: "Tulipa gesneriana",
    grip: { x: 0.469, y: 0.673 }, size: 3.92,
    meaning: "Forgiveness & fresh starts",
    story: "White tulips quietly say “let's begin again.” They are given to apologise, to close one chapter and open the next, or simply to wish someone a clean, bright start.",
    giveWhen: "A new job, a new home, or a heartfelt sorry.",
    palette: ["#F6F1E4", "#DCE5C4", "#7FA05A"],
  },
  {
    id: "tulip-putih-besar", name: "White tulip armful", latin: "Tulipa gesneriana",
    grip: { x: 0.509, y: 0.74 }, size: 2.64,
    meaning: "Peace & sincerity",
    story: "An armful of white tulips is a calm, generous gesture. It stands for honesty and peace of mind, a way of saying your feelings are simple and true.",
    giveWhen: "Weddings, graduations, or to someone who needs calm.",
    palette: ["#FBF8EF", "#E2E8CF", "#5E7D3E"],
  },
  {
    id: "tulip-pink", name: "Pink tulips", latin: "Tulipa gesneriana",
    grip: { x: 0.484, y: 0.809 }, size: 3.21,
    meaning: "Affection & good wishes",
    story: "Pink tulips carry warm, uncomplicated love: friendship, care and confidence in someone. They are the flower of “I'm happy you're here.”",
    giveWhen: "Birthdays, best friends, and congratulations.",
    palette: ["#F6B3C8", "#E57FA0", "#6E9B4A"],
  },
  {
    id: "tulip-pink-besar", name: "Blush tulips", latin: "Tulipa gesneriana",
    grip: { x: 0.475, y: 0.792 }, size: 2.95,
    meaning: "Caring & happiness",
    story: "Soft blush tulips are about tenderness: looking after someone and being glad for their joy. Gentle, sweet, never too loud.",
    giveWhen: "Get-well wishes or a thank-you to someone dear.",
    palette: ["#F4C6CF", "#E59AAE", "#7EA157"],
  },
  {
    id: "mawar-merah", name: "Red roses", latin: "Rosa",
    grip: { x: 0.51, y: 0.771 }, size: 3.29,
    meaning: "Deep, romantic love",
    story: "The classic declaration. A full bunch of red roses means passion and devotion, a love that isn't shy about being seen.",
    giveWhen: "Anniversaries, Valentine's Day, or a big confession.",
    palette: ["#B3122A", "#7D0A1C", "#4F7A3A"],
  },
  {
    id: "mawar-merah-tiga", name: "Three red roses", latin: "Rosa",
    grip: { x: 0.571, y: 0.719 }, size: 4.78,
    meaning: "“I love you”",
    story: "In the language of flowers, the number counts. Three red roses spell out three words: I love you. Small, simple, and very clear.",
    giveWhen: "Early dates and quiet, important moments.",
    palette: ["#C0172F", "#801022", "#5C8442"],
  },
  {
    id: "peony-putih", name: "White peonies", latin: "Paeonia lactiflora",
    grip: { x: 0.481, y: 0.746 }, size: 3.26,
    meaning: "Honour & a happy marriage",
    story: "Lush white peonies symbolise honour, good fortune and a happy union. They are a favourite in bridal bouquets for a reason.",
    giveWhen: "Weddings, engagements, and new parents.",
    palette: ["#FBF7F0", "#EDE3D4", "#6C8B4C"],
  },
  {
    id: "peony-blush", name: "Blush peonies", latin: "Paeonia lactiflora",
    grip: { x: 0.53, y: 0.756 }, size: 3.08,
    meaning: "Romance & bashfulness",
    story: "Legend says shy nymphs hid in peony petals, which is why blush peonies stand for romance with a little bit of blushing.",
    giveWhen: "A crush, a first date, or a sweet surprise.",
    palette: ["#F2D3D6", "#D9A5AE", "#5F7F48"],
  },
  {
    id: "peony-magenta", name: "Magenta peonies", latin: "Paeonia lactiflora",
    grip: { x: 0.521, y: 0.732 }, size: 2.9,
    meaning: "Prosperity & good fortune",
    story: "Called the “king of flowers” in China, bold peonies wish wealth, abundance and a life that keeps blooming.",
    giveWhen: "Openings, promotions, and Lunar New Year.",
    palette: ["#D22F6B", "#9E1D4E", "#5A7E3C"],
  },
  {
    id: "daisy", name: "Daisies", latin: "Leucanthemum",
    grip: { x: 0.486, y: 0.659 }, size: 3.19,
    meaning: "Innocence & loyal love",
    story: "Daisies are the “he loves me, he loves me not” flower: playful, honest, and loyal. They feel like a sunny walk in a field.",
    giveWhen: "Just because, or to a friend who makes you laugh.",
    palette: ["#FFFFFF", "#F4D35E", "#6F8F45"],
  },
  {
    id: "matahari", name: "Sunflowers", latin: "Helianthus annuus",
    grip: { x: 0.517, y: 0.692 }, size: 3.61,
    meaning: "Adoration & loyalty",
    story: "Sunflowers follow the sun across the sky, so they stand for devotion and staying true. Bright, happy and hard to be sad around.",
    giveWhen: "To your sunshine person, or anyone who needs a lift.",
    palette: ["#F7C531", "#C9861A", "#5D7F33"],
  },
  {
    id: "matahari-liar", name: "Wild sunflowers", latin: "Helianthus annuus",
    grip: { x: 0.512, y: 0.761 }, size: 2.96,
    meaning: "Warmth & optimism",
    story: "Loose, wild sunflowers feel like late summer. They wish someone warmth, hope and the energy to keep going.",
    giveWhen: "New adventures, road trips, or a tough week.",
    palette: ["#F1B825", "#8E5B14", "#647F3A"],
  },
  {
    id: "spider-lily", name: "Red spider lilies", latin: "Lycoris radiata",
    grip: { x: 0.516, y: 0.611 }, size: 3.73,
    meaning: "Farewell & longing",
    story: "In Japan the higanbana blooms at the autumn equinox along paths and riverbanks. Its flowers and leaves never appear at the same time, so it became a flower of goodbyes, of souls that can't meet, and of remembering someone.",
    giveWhen: "Remembrance and autumn, not as a gift in Japan, where it's thought unlucky.",
    palette: ["#C8102E", "#E9576A", "#6C8A3A"],
  },
  {
    id: "carnation-pink", name: "Pink carnations", latin: "Dianthus caryophyllus",
    grip: { x: 0.437, y: 0.78 }, size: 2.77,
    meaning: "A mother's love & gratitude",
    story: "Pink carnations are the classic Mother's Day flower: steady, tender love and thanks for being looked after. They last for weeks, just like the feeling.",
    giveWhen: "Mother's Day, or a thank-you to someone who raised you.",
    palette: ["#F2A7B4", "#E07A8F", "#8FA79A"],
  },
  {
    id: "calla-putih", name: "White calla lilies", latin: "Zantedeschia aethiopica",
    grip: { x: 0.465, y: 0.601 }, size: 3.94,
    meaning: "Elegance & purity",
    story: "With one smooth curling petal, the calla lily is pure line and grace. It is a favourite wedding flower and a symbol of rebirth and new beginnings.",
    giveWhen: "Weddings, a fresh start, or someone with quiet elegance.",
    palette: ["#FBF8F0", "#E8EBD6", "#5E8A3C"],
  },
  {
    id: "ranunculus", name: "Peach ranunculus", latin: "Ranunculus asiaticus",
    grip: { x: 0.486, y: 0.697 }, size: 2.48,
    meaning: "Radiant charm",
    story: "Layer upon layer of paper-thin petals: ranunculus says “I'm dazzled by your charms.” Soft, romantic and a little bit flirty.",
    giveWhen: "A crush, a first date, or someone who lights up the room.",
    palette: ["#F7B39A", "#EE8C7A", "#7DA24F"],
  },
  {
    id: "stargazer", name: "Stargazer lilies", latin: "Lilium 'Stargazer'",
    grip: { x: 0.48, y: 0.82 }, size: 3.03,
    meaning: "Ambition & encouragement",
    story: "Stargazers face up to the sky and fill a room with scent. Bold and confident, they stand for big dreams and the courage to chase them.",
    giveWhen: "Promotions, opening days, or someone aiming high.",
    palette: ["#F7C9D6", "#D9456F", "#3F6E2E"],
  },
  {
    id: "gerbera", name: "Gerbera daisies", latin: "Gerbera jamesonii",
    grip: { x: 0.497, y: 0.8 }, size: 3.05,
    meaning: "Cheerfulness & joy",
    story: "Gerberas are pure happiness in a flower: big round faces in candy colours. They are made for brightening someone's day.",
    giveWhen: "Get-well wishes, a bad week, or just to make someone smile.",
    palette: ["#F48C5A", "#E84A5F", "#6F9A3E"],
  },
].map(b => ({ ...b, src: `assets/flowers/${b.id}.png` }));
